### ISSUE TITLE
ReadMe described installation on Windows fails

### ISSUE THREAD

**Issue by d0m1987** [roapi/roapi#10]
Hi,

I tried to install roapi according to the ReadMe and the following error occured:

![image](https://user-images.githubusercontent.com/8297453/109274888-4bb89880-7814-11eb-85c7-01b66df14101.png)

Operating System: Windows 10.0.18363

I'm not fluent in Rust and just wanted to test this cool project. So, maybe this is something that an additional command parameter could solve? Would be great if information regarding this problem could be added to the ReadMe. Thanks!

**Comment by houqp** [comment]
@d0m1987 can you give the new install command a try? I missed a branch argument in it.

**Comment by d0m1987** [comment]
Works like a charm :-) Thanks @houqp for the fast help!
