### ISSUE TITLE
Error: no CA certificates found

### ISSUE THREAD

**Issue by xezpeleta** [roapi/roapi#103]
Hi,

When I configure a Google Spreadsheet using the Docker environment, I get the following error:

```
[2021-11-12T11:35:25Z INFO  roapi_http::api] loading `uri(https://docs.google.com/spreadsheets/d/<redacted>)` as table `<redacted>`
thread 'main' panicked at 'no CA certificates found', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/hyper-rustls-0.22.1/src/connector.rs:45:13
```

Installing the package `ca-certificates` with APT in the Docker image fixed the issue.

Thanks

**Comment by houqp** [comment]
good catch @xezpeleta , looks like should be a very simple fix. adding `good-first-issue` to it.
