### ISSUE TITLE
Expecting qualified names

### ISSUE THREAD

**Issue by Seddryck** [roapi/roapi#110]
Hi all,

I'm using the version 0.4.4 and the REST API and was able to successfully use roapi using a projection/sort/limit pattern with the following call:
`curl -v "http://127.0.0.1:8084/api/tables/cities?&columns=City,State&sort=LatD&limit=3"`

Unfortunately, when I run more than once this call, I'm starting to receive such messages: `{"code":400,"error":"query_execution","message":"Failed to execute query: Error during planning: No field named 'cities.LatD'. Valid fields are 'cities.City', 'cities.State'."}* Connection #0 to host 127.0.0.1 left intact`

More, I can't successfully qualify the names of the columns, I tried many variationq but without success:
`curl -v "http://127.0.0.1:8084/api/tables/cities?&sort=LatD&columns=cities.City,cities.State&limit=3"` which is misleading regarding that the error statement is claiming that the expected fields are 'cities.City', 'cities.State'.

Any direction will be welcome.

**Comment by houqp** [comment]
What dataset did you use for the testing? Is it something you can share for us to reproduce the error?

**Comment by Seddryck** [comment]
Yes surely. Here you are:
[cities.csv](https://github.com/roapi/roapi/files/7582433/cities.csv)

**Comment by Seddryck** [comment]
I tested with v0.5.0 and same result.

**Comment by houqp** [comment]
oh i see, this is a known restriction in datafusion, columns in the filter clause need to present in the projection clause as well :( Try this `curl -v "http://127.0.0.1:8084/api/tables/cities?&columns=City,State,LatD&sort=LatD&limit=3"`.

**Comment by Seddryck** [comment]
Thx for forwarding the issue to datafusion. Apply your change, I don't get any error 400 when I change the projection to include the filtered columns but I don't get the right result :-s (as you can see the result is changing from a call to the next).

![image](https://user-images.githubusercontent.com/5455045/142988797-7a794892-e2ac-476f-a000-a316816080c1.png)

As you can see the result si changing. Based on your previous answer, the fact that sometimes I get the right result, sometimes it's wrong ... should I understand that the operations filter, limit and projection are executed in parallel?

**Comment by houqp** [comment]
good catch @Seddryck , https://github.com/roapi/roapi/pull/114/files should take care of that.

**Comment by Seddryck** [comment]
Tried to build from source code in order to validate the fix but was having some issues with `cargo build` regarding the patches provided in cargo.toml and not enough experience in rust to fix it (and my googlefu didn't help).

Anyway, I reviewed the code and also checked the feedback on apache/arrow-datafusion#1351 based on these elements, I think that the initial issue that I reported where ROAPI was claiming it didn't find out the column in the current dataset is not a datafusion bug but a ROAPI one. With the same idea than the limit should be applied after the filter, the filter should be applied **before** the projection. At the moment this constraint is not formulated (as far as I understand rust code at https://github.com/roapi/roapi/blob/c1ae60d667d77724c43e56ac2bd59d9acae67783/columnq/src/query/rest.rs#L70).

IMO, regarding the limited complexity of queries that can be provided by the means of the rest API, I think that the operations' order should always be deterministic:

1. Filter
2. Sort (Filtering before will decrease the length of dataset before sorting which can only be a good idea)
3. Limit (Limit after sort to guarantee correct result but before projection to decrease the length of the dataset)
4. Projection (Should be done late to avoid filtering out some columns used in the filter or sort operations)

Just my thoughts, feel free to disagree I'm probably missing some experience with this code base.

**Comment by houqp** [comment]
Sorry for the delay due to vacation. Thanks @Seddryck for the deep dive, turns out I filed the wrong issue upstream. Filter works just fine regardless of order due to the filter push down optimization rule. It was the sort clause that was causing issue, so I filed a new upstream ticket to capture that.

I agree with you that orders of operations should be deterministic. I think we should take it one step further and make it consistent across different query interfaces as well include REST, GraphQL and SQL. In terms of the order, I think projection should come before sort so we can avoid performing unnecessary sorting on unprojected columns. The query engine itself should be smart enough to handle unprojected sorting columns.

**Comment by Seddryck** [comment]
No problem! Agree if query engine is smart enough to handle cases where the sort columns are not projected, smarter to project before sorting.

**Comment by Seddryck** [comment]
I confirm that #115 is fixing the issue related to the limit applied before the sorting operation leading to wrong results. Thanks for the work done! 

I'm keeping an eye on apache/arrow-datafusion#1372 to fix the issue around sorting data on unprojected column.
