### ISSUE TITLE
consistent and deterministic logical plan construction across query interfaces

### ISSUE THREAD

**Issue by houqp** [roapi/roapi#115]
Follow on for https://github.com/roapi/roapi/issues/110. Order of logical plan node should be applied in a consistent and deterministic order between different query interfaces.

Here is the order we have in the sql planner today, would be good to keep the REST and GraphQL query interface in sync on this as well:

1. filter
2. project/select
3. sort
4. limit

**Comment by Seddryck** [comment]
Pay attention that if you first project then after sort, the columns on which you're executing your sort could not be available anymore in your dataset (expl: project on `City and State` but Sort on `Latitude`).

**Comment by yfaming** [comment]
Hello, may I take this one?😀

**Comment by houqp** [comment]
go ahead @yfaming !
