### ISSUE TITLE
columnq binary version information does not match Release page version information

### ISSUE THREAD

**Issue by chrisfw** [roapi/roapi#116]
Release page for most recent asset tar.gz ->  **columnq-cli-v0.2.0**

Output from downloaded Windows binary:  

PS C:\temp\jira> columnq --version
**Columnq 0.0.1**

**Comment by houqp** [comment]
thanks @chrisfw for the report, turns out the version was hardcoded in the source code and never got updated. I have sent a PR to make sure this is taken care of automatically in future releases.

**Comment by chrisfw** [comment]
No problem.  Thank you for your prompt response!  Sounds good.
