### ISSUE TITLE
Add HTTP2 integration test in CI

### ISSUE THREAD

**Issue by houqp** [roapi/roapi#120]
to make sure we don't have regression on dropping support for http2 going forward. The test can just be a simple http2 curl call to roapi.

**Comment by novemberkilo** [comment]
Hey @houqp happy to take this on next if that's ok? Please feel free to assign to me.

**Comment by houqp** [comment]
sure, thanks!

**Comment by novemberkilo** [comment]
So I've played around with this a bit and early indications are that testing `localhost:8000` for HTTP/2 is not likely to yield results unless we figure out how to run up a server with TLS. 

For example:

```
~ % curl -v --http2 localhost:8080/api/schema
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /api/schema HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.80.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json
< content-length: 6579
< date: Fri, 03 Dec 2021 06:22:48 GMT
<
{"uk_cities":{"fields":[<snip>
```

**Comment by novemberkilo** [comment]
Update: I've got a possible solution that I would like to sketch out. Essentially I would like to do the following in an integration test:

```
~ % curl -sI --http2-prior-knowledge localhost:8080/api/schema -o/dev/null -w '%{http_version}\n'
2
```

So I will check that the curl command there will return `2` (it returns `1.1` if the server does not support HTTP/2).

Notes:

When you use `http2-prior-knowledge` you are essentially saying that I expect my server to respond with HTTP/2 and I do not want to degrade to HTTP/1.1. See: 

https://everything.curl.dev/http/http2
https://curl.se/docs/http2.html#:~:text=curl%20offers%20the%20%2D%2Dhttp2%2Dprior%2Dknowledge%20command%20line%20option,by%20default%20for%20HTTPS%20connections.

**Comment by ekroon** [comment]
@novemberkilo There are already some integration tests that use Reqwest. There is an option to set the HTTP version on the request: https://docs.rs/reqwest/latest/reqwest/struct.RequestBuilder.html#method.version

Maybe that will do as well?

**Comment by houqp** [comment]
that `http2-prior-knowledge` option is very cool, thanks @novemberkilo for discovering that :D . I am cool with us going either way (curl v.s. reqwest) as long as we are testing http2 end to end.
