### ISSUE TITLE
JSON only parses 8192 rows?

### ISSUE THREAD

**Issue by PsypherPunk** [roapi/roapi#132]
I'm looking at the dataset located here: https://covid19.who.int/who-data/countries-by-day.json

It takes a little coercing (keys are a combination of the `dimensions` and `metrics` values, the data are in `rows`) but I've turned it into a CSV file and loaded it into `roapi` and all is good, 178,935 rows in the resulting API.

However, having similarly converted it to a more conventional JSON structure, `roapi` doesn't seem to serve all the records, only holding 8,192 rows (I'd presume this was an error in the conversion were it not for the fact that this `batch_size` used internally.)

**Comment by PsypherPunk** [comment]
I've tried this again with a dummy JSON file created with more than 8,192 rows and the same thing appears to happen (though not with a similarly-size CSV file):

```python
import json
with open("test.json", "w") as o:
    json.dump([{"a": "b"} for _ in range(8192 * 2)], o)
```

Then running `cargo run --bin roapi-http -- --table=test.json` and counting the rows returned:

```bash
$ curl --silent "http://127.0.0.1:8080/api/tables/test" | jq | grep a | wc -l
8192
```

**Comment by houqp** [comment]
Thanks @PsypherPunk , I found the bug and will get it fixed by end of today.

**Comment by PsypherPunk** [comment]
Amazing—thanks, @houqp!
