### ISSUE TITLE
Fields omitted for null values?

### ISSUE THREAD

**Issue by PsypherPunk** [roapi/roapi#134]
Thanks again for fixing #132. I'm still tinkering and noticed that when validating the CSV vs. JSON outputs the record-count didn't seem to tally when I was checking for certain fields.

It seems that if a field has a `null` value in the input CSV or JSON, that field is omitted from the output rather than being set to `null`.

For example:

CSV, integer values, empty field:

```csv
a
1
""
```

(CSV, string values don't really have a `null` value and work as expected.)

JSON, integer values, null field:

```json
[{"a": 1}, {"a": null}]
```

JSON, string values, null field:

```json
[{"a": "b"}, {"a": null}]
```

In all of the above cases the `a` field is dropped from the output in the latter record:

```bash
❯ curl --silent "http://127.0.0.1:8080/api/tables/test" 
[{"a":"b"},{}]
```

```bash
❯ curl --silent "http://127.0.0.1:8080/api/tables/test" 
[{"a":1},{}]
```

Not sure if this is a bug, expected behaviour or an issue with with underlying data parsing…?

**Comment by houqp** [comment]
Yes, this is expected behavior to save space, see https://github.com/apache/arrow-rs/blob/4b7afa6fea22b85fc6f1fe8548587c451d150440/arrow/src/json/writer.rs#L292.

What's your use-case for keeping the null value?

**Comment by PsypherPunk** [comment]
Aha! Thanks, @houqp.

I suppose it's down to how representative the response is—there are now two possible states that could result in the same thing:

```json
[{"a": "b"}, {"a": null},{}]
```

Is the missing `a` field now a result of the original `a` being `null`? Or the field being absent entirely? It's not possible to answer without referring back to the original data.

Not a major issue and good to know.—happy to close this. Again, thanks.

**Comment by houqp** [comment]
Typically in OLTP systems, if a field is missing from the underlying data file, the query engine will backfill that column with null so the response schema is always consistent. In this case, you can consider it backfilled the missing column, then subsequently removed all the null columns to reduce payload size :)
