### ISSUE TITLE
excel support example or clarification

### ISSUE THREAD

**Issue by alperyilmaz** [roapi/roapi#139]
First of all, kudos and bravo for such a great idea!

From the documentation, it mentions Excel is supported. When I tried to use `.xls` or `.xlsx` files I got following error: `Error: Invalid table URI: unsupported extension in uri`

Do Excel files supported? Is there an example code about using Excel files? I checked Datafusion site as well but couldn't find one.

**Comment by tiphaineruy** [comment]
If you look at the README you'll see that the implementation for Excel is not done. 
Your best bet is just exporting the data as CSV.

**Comment by alperyilmaz** [comment]
oh I see.. I totally missed that.. looking at the diagram on top of README I thought it was supported.. 
Looking at the implementation list, Excel support is coming in near future I guess..
