### ISSUE TITLE
Parquet Str

### ISSUE THREAD

**Issue by tiphaineruy** [roapi/roapi#143]
**Describe the bug**

When reading a parquet file:
thread 'tokio-runtime-worker' panicked at 'Unsupported datatype: LargeUtf8',
.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.3.0/src/json/writer.rs:490:13

**To Reproduce**

http request with json response on a parquet str field

**Expected behavior**

Json properly returned

**Additional context**

Parquet str are read as Large_utf8 and the arrow json writer does'nt like it, even if they were written to parquet as Utf8. 
I've not found a way in the conf  to cast columns before generating the request but is could be a usefull addition

**Comment by houqp** [comment]
This should be a simple fix upstream by adding a branch for LargeUtf8 around https://github.com/apache/arrow-rs/blob/a69f0d119c67ef19e6a61acd24359de1b4ed2e10/arrow/src/json/writer.rs#L161. @tiphaineruy are you interested in sending a PR over?

**Comment by tiphaineruy** [comment]
@houqp 
https://github.com/apache/arrow-rs/pull/1358

**Comment by houqp** [comment]
Thank you @tiphaineruy , that was quick :D
