### ISSUE TITLE
datafusion-objectstore-s3

### ISSUE THREAD

**Issue by tiphaineruy** [roapi/roapi#144]
Currently ColumnQ uses rusoto

A lot has been done with Object stores on datafusion and I'm wondering if it could be interesting to move to:
https://github.com/datafusion-contrib/datafusion-objectstore-s3

**Comment by houqp** [comment]
Yes, PRs welcome :) I think we need to update datafusion to the latest version first. I am happy to provide guidance for anyone who is interested in this.

**Comment by tiphaineruy** [comment]
Started Bumping version  to allow further work on S3 and getting latest datafusion improvement.

Stopped because I'm not sure what to do with your patches

```

[patch.crates-io]
datafusion = { git = "https://github.com/houqp/arrow-datafusion.git", rev = "50a98805cdd6d5383f0c124d449ed549ca13428a" }
# datafusion = { path = "/home/houqp/Documents/code/delta/arrow-datafusion/datafusion" }

deltalake = { git = "https://github.com/delta-io/delta-rs.git", rev = "70f520a15ae7884c46142bfb0dbc8790f43d8701" }

[patch."https://github.com/apache/arrow-datafusion"]
datafusion = { git = "https://github.com/houqp/arrow-datafusion.git", rev = "50a98805cdd6d5383f0c124d449ed549ca13428a" }
# datafusion = { path = "/home/houqp/Documents/code/delta/arrow-datafusion/datafusion" }
```

That reference your Forks.

**Comment by houqp** [comment]
You can ignore my fork, I don't have any custom datafusion patch there anymore :) Using the latest upstream master commit should work just fine.

**Comment by Dandandan** [comment]
@tiphaineruy FYI, I upgraded delta-rs to the latest DataFusion version (main branch, latest commit).

**Comment by tiphaineruy** [comment]
Haha Thanks, I was wrangling with cargo and was going to open an isue in delta

**Comment by houqp** [comment]
just in time update from @Dandandan :D

**Comment by tiphaineruy** [comment]
I've bump most of what I could in the dependencies.
I think this can be merged.
I've almost halved the querytime on some of my request with the latest datafusion  🎉 .

I've noted some issues in the pr that might need an issue opened in datafusion.

The build time has exploded though. Might have to feature gate providers at some point.

**Comment by houqp** [comment]
@tiphaineruy i fully support introducing more feature gates in dataufsion :+1:
