### ISSUE TITLE
Hide table update endpoint behind a feature flag

### ISSUE THREAD

**Issue by houqp** [roapi/roapi#155]
By default, we should start roapi-http with update endpoint disabled so for read-only users, they won't need to pay the locking overhead and spend extra efforts to secure the write endpoint.

**Comment by zemelLeong** [comment]
How to judge whether it is read-only? Add a startup parameters?

**Comment by zemelLeong** [comment]
I'll try for this.

**Comment by houqp** [comment]
yeah, we can add a new flag to roapi-http cli :)

**Comment by houqp** [comment]
fixed by @zemelLeong in #154
