### ISSUE TITLE
I want to add MySQL support, what ORM library is better?

### ISSUE THREAD

**Issue by zemelLeong** [roapi/roapi#157]
I have only used diesel. I'm not sure if it is appropriate to use here.

**Comment by houqp** [comment]
I recommend giving https://github.com/sfu-db/connector-x a try ;) It supports all major relational databases.

**Comment by jychen7** [comment]
thanks @zemelLeong for contribution https://github.com/roapi/roapi/pull/162, I think we can close it.
Feel free to re-open if need
