### ISSUE TITLE
HTTP2 Support

### ISSUE THREAD

**Issue by snghnishant** [roapi/roapi#16]
I was wondering if the maintainers can add HTTP2 support as a feature request. So it can be worked later to be added to the framework.
Thanks.

**Comment by houqp** [comment]
ROAPI uses actix-web and looks like it's not too much work to configure this: https://actix.rs/docs/http2/.

**Comment by novemberkilo** [comment]
@houqp Hi - I am fishing around for an issue to pick up to begin contributing to `roapi` 

Now that the switch has been made to `axum` is this still an issue and if so, is it still a good-first-issue. If so, and if it's appropriate to pick up, I'd like to give it a go. It looks like it might involve turning on the `http2` flag for axum https://docs.rs/axum/latest/axum/#feature-flags

**Comment by houqp** [comment]
Thanks @novemberkilo ! Based on the axum doc, it does look like a simple change. If you are interested in giving it a try, please go for it.
