### ISSUE TITLE
Document support for sqlite

### ISSUE THREAD

**Issue by houqp** [roapi/roapi#163]
Now that @zemelLeong has added support for both mysql and sqlite, we should make sure to update docs and design diagram to reflect that.

**Comment by zemelLeong** [comment]
Seems that this https://github.com/roapi/docs.git needs to be updated. I'll do that in this weekend.

**Comment by jychen7** [comment]
closed? looks like it is done at 2022-05-30 https://github.com/roapi/docs/blob/main/src/config/databases.md

**Comment by jychen7** [comment]
I will close it first.
Feel free to re-open if need
