### ISSUE TITLE
Compile with simd feature

### ISSUE THREAD

**Issue by tiphaineruy** [roapi/roapi#176]
I wanted to try the sqlite table feature,

Realised that the feature is not enabled by default on the build pushed to brew.

And ran into this error while building the lib with the  following command:

> info: The currently active `rustc` version is `rustc 1.63.0-nightly (dc80ca78b 2022-06-21)`

```
RUSTFLAGS='-C target-cpu=native' cargo +nightly build --release --features default,simd,database
```
and got:

```
error: expected one of `!` or `::`, found keyword `mod`
   --> /Users/tiphaineruy/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.7/src/lib.rs:347:7
    |
347 | crate mod llvm {
    |       ^^^ expected one of `!` or `::`
```

Project compiles fine without the  simd feature.

Probably a macos quirk.

**Comment by geoHeil** [comment]
see the issue over there https://github.com/roapi/roapi/issues/178 perhaps we can merge the discussion?

**Comment by houqp** [comment]
this should have been fixed
