### ISSUE TITLE
roapi postgres support - JDBC driver fails due to issuing Postgres session command to set extra float digits

### ISSUE THREAD

**Issue by chrisfw** [roapi/roapi#180]
Hi,
This appears to be a command that is automatically issued by the postgres JDBC driver and the error returned by roapi prevents a successful connection in DBeaver

```
[2022-07-22T13:12:27Z INFO  roapi::server::postgres] preparing query: SET extra_float_digits = 3
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionClosed', D:\a\roapi\roapi\roapi\src\server\postgres.rs:114:40
```
Can support for this statement be added even if it is a no-op?

Thanks,
Chris Whelan

**Comment by houqp** [comment]
yeah, good idea, should parse and ignore this command :+1:
