### ISSUE TITLE
Connection error for Wasabi storage(AWS S3 bit-compatible)

### ISSUE THREAD

**Issue by 100mi** [roapi/roapi#185]
### Title
Issue while connecting to [Wasabi storage](https://wasabi.com/) while following the documentation as mentioned for [BLOB-s3](https://roapi.github.io/docs/config/blob-store.html#s3)

### Description
- All the required env variables were regarded to Access key, Secret key and region were already set as env variables.
- The following yaml config file was used first as mentioned below as `s3.yml`: 

```yml
addr:
  http: 
  postgres: 
tables:
  - name: "allotment_offtake_wheat"
    uri: "s3://fci-factly/processed/allotment_offtake/wheat/2021-22/output.csv"
    option:
        format: "csv"
        use_memory_table: false
  - name: "allotment_offtake_rice"
    uri: "s3://fci-factly/processed/allotment_offtake/rice/2021-22/output.csv"
    option:
        format: "csv"
        use_memory_table: false
```
But this lead to an error for : 
```zsh
➜  roapi git:(main) ✗ roapi -c test_data/s3.yml
[2022-08-22T09:58:40Z INFO  roapi::context] loading `uri(s3://fci-factly/processed/allotment_offtake/wheat/2021-22/output.csv)` as table `allotment_offtake_wheat`
Error: Error loading data from S3 store: Failed to list bucket: Request ID: None Body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>P11LOWDB3U7VE85SZ9Z4</AWSAccessKeyId><RequestId>A881EF38M4TFN38B</RequestId><HostId>5Nf65CG/0jhRBLgewdli0Zp2GepzzZUBLQvHoSsI41lq7Fr36X6BnzfCFJDq0wHI+7Uofk5gi5I=</HostId></Error>
```
- With the next genuine approach we tried to differ the end point url from `s3://fci-factly/processed/allotment_offtake/wheat/2021-22/output.csv` to something like `s3.eu-central-1.wasabisys.com://fci-factly/processed/allotment_offtake/wheat/2021-22/output.csv`. But there is a new error looks like : 
```zsh
➜  roapi git:(main) ✗ roapi -c test_data/s3.yml
[2022-08-22T10:00:29Z INFO  roapi::context] loading `uri(s3.eu-central-1.wasabisys.com://fci-factly/processed/allotment_offtake/wheat/2021-22/output.csv)` as table `allotment_offtake_wheat`
Error: Invalid table URI: Unsupported scheme: Some(Unregistered(UnregisteredScheme { normalized: true, scheme: "s3.eu-central-1.wasabisys.com" }))
```

Thanks in advance, and do let me know for any further or descriptive information required.

**Comment by houqp** [comment]
thanks for the report! could you also share with me what environment variables you set for the S3 auth? specifically, have you tried setting the `AWS_ENDPOINT_URL` environment variable?

**Comment by houqp** [comment]
code that handles endpoint overwrite FWIW: 
https://github.com/roapi/roapi/blob/5972467cbb59985b9723aa38a32ea61a8751ac30/columnq/src/io/s3.rs#L204
