### ISSUE TITLE
Do `columnq` build instructions need to be updated?

### ISSUE THREAD

**Issue by herbygillot** [roapi/roapi#192]
The current instructions say:

```
cargo install --locked --git https://github.com/roapi/roapi --branch main --bin columnq-cli
```

But I'm getting:

```
error: no bin target named `columnq-cli`
```

Should it be `--bin columnq` instead?

That's what I see in `columnq-cli/Cargo.toml`:
https://github.com/roapi/roapi/blob/021332de5d75deaff7641b47e60ac224332ca287/columnq-cli/Cargo.toml#L10-L11

**Comment by houqp** [comment]
Hi, you might be reading an old version of the readme, the instruction has been fixed yesterday :)
