### ISSUE TITLE
LENGTH() of columnq-cli returns wrong value by passing multple code points char(ie. emoji)

### ISSUE THREAD

**Issue by hankei6km** [roapi/roapi#197]
Hi.
I am trying columnq-cli with data that contains Japanese characters.
And I think it's a good tool.

However, `LENGTH()` (and `CHAR_LENGTH()`) returns an wrong value for emoji, etc.

## Environment

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```
$ columnq -V
Columnq 0.3.0
```

## Steps to reproduce

`chklen.json`([chklen.zip](https://github.com/roapi/roapi/files/9692109/chklen.zip))
```json
[
  { "id": 1, "ch": "a" },
  { "id": 2, "ch": "あ" },
  { "id": 3, "ch": "😊" },
  { "id": 4, "ch": "❤️" },
  { "id": 5, "ch": "👨‍👨‍👧‍👦" },
  { "id": 6, "ch": "記" },
  { "id": 7, "ch": "記󠄂" }
]
```

![chklen](https://user-images.githubusercontent.com/1386689/193446394-8efdbe4e-0028-482e-8b55-9ca5fe97cd28.png)

Run select
```sh
$  columnq sql --table chklen.json "SELECT id, ch, CHAR_LENGTH(ch) as len FROM chklen;" > res.txt
```

`res.txt`
```
+----+----------+-----+
| id | ch       | len |
+----+----------+-----+
| 1  | a        | 1   |
| 2  | あ       | 1   |
| 3  | 😊       | 1   |
| 4  | ❤️        | 2   |
| 5  | 👨‍👨‍👧‍👦 | 7   |
| 6  | 記       | 1   |
| 7  | 記󠄂       | 2   |
+----+----------+-----+
```

![res](https://user-images.githubusercontent.com/1386689/193446416-15b905b6-d107-46ac-b5d8-b4896e3dc369.png)

The character with id "4" ”5" and "7' has a wrong  len value(The correct length for each character is `1`).
It seems that characters with "️Variation Selector" cannot be counted correctly.

detail of "❤️"

https://emojipedia.org/red-heart/
https://emojipedia.org/emoji/%E2%9D%A4/
https://emojipedia.org/emoji/%EF%B8%8F/

And "ch" of "id:7" also contains a selector.

**Comment by houqp** [comment]
Thanks for the report @hankei6km , I believe this is expected behavior because `CHAR_LENGTH` counts number of bytes. If you run the same query in MySQL, you will get the same result.
