### ISSUE TITLE
optimize IO with bufreader

### ISSUE THREAD

**Issue by houqp** [roapi/roapi#20]
When loading dataset from filesystem and network, we should use `BufReader` instead of `Read` trait to reduce system calls. This means `partitions_from_uri` functions' signatures need to be changed to accept a callback that takes `BufReader` instead of `Read`.

**Comment by tobyhede** [comment]
Hello 👋 ... went to pick this one up and just wanted to check. 

The File System partitions_from_uri was straightforward, but some of the other functions are a bit more complicated. 

Functions like the `S3::partitions_from_uri` expect a callback with the type `FnMut(:Cursor<Vec<u8>>)`

Digging further into the way S3 subsystem works, the core is a ByteStream that is read and wrapped into a Cursor ... does this need to be wrapped again into  `BufReader` -> `FnMut(BufReader<Cursor<Vec<u8>>>)`?

It makes sense from a consistency perspective, - each partitions_from_uri function returning a BufReader that wraps whatever the underlying system is loading (file, byte stream etc).  In the case of the byte stream and cursor does it provide any optimization benefit?

**Comment by tobyhede** [comment]
Perhaps I will push what I have and take it from there.

**Comment by houqp** [comment]
I believe this is already taken care by @tobyhede :heart:
