### ISSUE TITLE
GraphQL/REST query operator (limit) not working

### ISSUE THREAD

**Issue by leodido** [roapi/roapi#220]
While trying this fine art piece of software I hit a bug.

Namely, the `limit` argument when using the GraphQL endpoint doesn't work. In fact, the following query returns all the records of the `uk_cities` table.

```bash
curl -X POST -d "query { uk_cities(limit: 2) {city, lat, lng} }" localhost:8080/api/graphql
```

May have to do with the recent upgrade to Datafusion 12?

I'm using v0.8.0

**Comment by leodido** [comment]
Notice that the only difference from your README examples is that I'm dynamically loading the `uk_cities` table from the internet.

Like so:

```bash
curl -X POST localhost:8080/api/table \
    -H 'Content-Type: application/json' \
    -d '[
    {
        "tableName": "uk_cities",
        "uri": "https://raw.githubusercontent.com/roapi/roapi/main/test_data/uk_cities_with_headers.csv"
    }
    ]
```

**Comment by elliot14A** [comment]
Hello, I faced similar issue. I just went through the columnq code and found out that in all the querying methods the skip and limit parameters were swapped.
For example in the file columnq/src/query/rest.rs in the function table_query_to_df you will find this:

```
if let Some(val) = params.get("limit") {
        let limit = val.parse::<usize>().map_err(num_parse_err)?;
        df = df.limit(limit, None).map_err(QueryError::invalid_limit)?;
    }
```

change it to:
```
if let Some(val) = params.get("limit") {
        let limit = val.parse::<usize>().map_err(num_parse_err)?;
        df = df.limit(0, Some(limit)).map_err(QueryError::invalid_limit)?;
    }
```
If you make these changes it will work as required!!
