### ISSUE TITLE
Issue: Queries load results into memory

### ISSUE THREAD

**Issue by elliot14A** [roapi/roapi#232]
Currently all queries load the results in to memory
```
//in columnq/query/grapqhl.rs
pub async fn exec_query(
    dfctx: &datafusion::execution::context::SessionContext,
    q: &str,
) -> Result<Vec<arrow::record_batch::RecordBatch>, QueryError> {
    query_to_df(dfctx, q)?
        .collect()
        .await
        .map_err(QueryError::query_exec)
}
// columnq/query/rest.ts
pub async fn query_table(
    dfctx: &datafusion::execution::context::SessionContext,
    table_name: &str,
    params: &HashMap<String, String>,
) -> Result<Vec<RecordBatch>, QueryError> {
    let df = table_query_to_df(dfctx, table_name, params)?;
    df.collect().await.map_err(QueryError::query_exec)
}
```
So all this queries use a method called `collect` which as per docs loads the queried results in to memory.
```
Convert the logical plan represented by this DataFrame into a physical plan and execute it, collecting all resulting batches into memory Executes this DataFrame and collects all results into a vector of RecordBatch.
```

There is another method called `collect_partitioned` which does not load into the memory but return the result `Result<Vec<Vec<RecordBatch>>>`
```
xecutes this DataFrame and collects all results into a vector of vector of RecordBatch maintaining the input partitioning.
```

So can I create pr changing current query functions with `collect_partitioned` method or can you just any other alternatives to perform queries while not loading them into memory?
thank you

**Comment by elliot14A** [comment]
With the  `collect` function, what happens to memory after querying , is it freed right after execution or  is the memory used when the same query is executed again?

What would be a better option to use, a redis cache or to use this query memory(if memory from query is used again)?

**Comment by houqp** [comment]
they should be the same in terms of memory usage, all of them load result data into memory. to reduce memory usage, you can do the following:

* use table config to disable memory table so every query to that particular table hits backing object store
* partition your data based on common query pattern so datafusion can perform filter push down to avoid reading files that are not covered by the query. For example, if your query filters by date, then you can partition the files as `s3://table/date=2023-01-01/uuid.csv`.

**Comment by houqp** [comment]
this should have been fixed for object store backed tables thanks to @jychen7 , @elliot14A please feel free to reopen the issue if you are still running into memory issues.
