### ISSUE TITLE
`SQL like '%中文%'` is not supported

### ISSUE THREAD

**Issue by tempbottle** [roapi/roapi#233]
http rest api give message:
`Failed to execute query: Arrow error: External error: Arrow error: External error: Execution error: Arrow error: External error: Internal error: Data type LargeUtf8 not supported for scalar operation 'like' on string array. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker`

Maybe DataFusion not support this.

**Comment by houqp** [comment]
This is now fixed in datafusion and the latest roapi release.
