### ISSUE TITLE
Upgrade to Datafusion v19

### ISSUE THREAD

**Issue by jychen7** [roapi/roapi#263]
### Background
Datafusion v19.rc1 by default turn on parallel scan on parquet files. ClickBench suggests almost 2x speed up in general.

### Goal
Upgrade to Datafusion v19 ~.rc1~

### Note
can refererence to https://github.com/roapi/roapi/pull/242

cc @houqp , may need help on updating on https://github.com/delta-io/delta-rs and https://github.com/roapi/connector-x

**Comment by houqp** [comment]
please feel free to ping me if you need any help in update these upstream dependencies :)

**Comment by houqp** [comment]
fixed with #279
