### ISSUE TITLE
Missing connector-x submodules have broken the build

### ISSUE THREAD

**Issue by rtyler** [roapi/roapi#271]
It's worth updating the forked `connector-x`. There's a submodule (federated-query) which has disappeared from GitHub and this causes `HEAD` to not be buildable anymore. More context: 

See: https://github.com/sfu-db/connector-x/issues/479

**Comment by houqp** [comment]
good call! will look into this after i help unblock https://github.com/roapi/roapi/pull/264 if no one gets to it til then.
