### ISSUE TITLE
Allow engine (datafusion) configuration in roapi yaml

### ISSUE THREAD

**Issue by chitralverma** [roapi/roapi#274]
Referring to the [configuration section](https://arrow.apache.org/datafusion/user-guide/configs.html) of datafusion docs. I was thinking if we should allow the end users to set options on the roapi server level set options like change of dialect etc.

This would look something like the below in the YAML config.
```
addr:
    ...

tables:
    ...

configuration:
    datafusion:
        sql_parser.dialect: "Hive"
        explain.physical_plan_only: true
        ...

```

**Comment by houqp** [comment]
Great idea :+1:

**Comment by holicc** [comment]
can i take a stab at this ?

**Comment by chitralverma** [comment]
go for it! let me know if you need help reviewing it.

**Comment by houqp** [comment]
fixed by @holicc
