### ISSUE TITLE
Automate docker release with Github action

### ISSUE THREAD

**Issue by houqp** [roapi/roapi#28]
add a job in roapi_http_release action to build, tag and push docker image to https://github.com/orgs/roapi/packages/container/package/roapi-http on every release.

**Comment by ekroon** [comment]
This is issue seems to be resolved with: https://github.com/roapi/roapi/commit/aff94fa6162afa8f109971ebd40b9f4a25460377

**Comment by houqp** [comment]
Yes, good call, this has been resolved.
