### ISSUE TITLE
I want to build roapi cloud

### ISSUE THREAD

**Issue by yuping322** [roapi/roapi#283]
HI:
    roapi is a great product。I have a lot of scattered files on my local computer, and it's inconvenient to register them every time when I start up. I want to create a cloud service based on roapi, offering some free quotas for users to use. Can I leave my contact information to chat about this? 
   my wechat: jimmywithu

**Comment by houqp** [comment]
hi @yuping322 , roapi is open-sourced under the MIT license, so you are free to use the code for building SASS services. I look forward to you contributing improvements back to upstream!
