### ISSUE TITLE
Is ROAPI supporting mysql connection

### ISSUE THREAD

**Issue by pravinparab** [roapi/roapi#292]
Hi ,

I am trying to load mysql table into ROAPI

Please find below code and result

**addr:
  # binding address for TCP port that speaks HTTP protocol
  http: 0.0.0.0:8084
  # binding address for TCP port that speaks Postgres wire protocol
  postgres: 0.0.0.0:5432
tables:
  - name: "ps_plugins_mst"
    uri: "mysql://username:password@localhost:3330/database"**

Result :

**Error: Database error: MySQL database feature not enabled.**

**Comment by pravinparab** [comment]
Any update on above issue

**Comment by houqp** [comment]
How did you install roapi? looks like the version you have is not built with the mysql feature flag.

**Comment by houqp** [comment]
Please reopen if the latest version doesn't work for you.

**Comment by atomotic** [comment]
The latest binary doesn't work with MySQL for me either.

```
./roapi --version
roapi 0.10.0
```

```
./roapi -c roapi.yml
[2024-02-06T10:54:21Z INFO  roapi::context] loading `uri(mysql://dba:xxxxxxx@xxxxx:3306/staging)` as table `staging`
thread 'main' panicked at /__w/roapi/roapi/roapi/src/startup.rs:63:14:
Failed to create Roapi context: Whatever { source: Some(TableError { source: Extension { msg: "unsupported extension in uri: mysql://dba:xxxxxxx@xxxxx:3306/staging" } }), message: "Failed to load table", backtrace: Backtrace(()) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by accforgithubtest** [comment]
@houqp - I see the same issue that @atomotic is seeing. 
I installed roapi via docker compose, using the latest version. 

Are there any additional configurations that need to be enabled to get mysql connections to work ?
