### ISSUE TITLE
update datafusion & arrow

### ISSUE THREAD

**Issue by xhwhis** [roapi/roapi#298]
I want to try updating datafusion and arrow by a few versions. Although I'm not clear on the benefits of doing so, I want to understand roapi better and make some contributions.

**Comment by houqp** [comment]
Thank you @xhwhis , I have a branch that's almost done at https://github.com/roapi/roapi/pull/297. Please feel free to help debug the last remaining CI issue and push it over the finish line!

**Comment by houqp** [comment]
closed with #297

**Comment by houqp** [comment]
Thanks for offering your help @xhwhis , there are more many more good first issues you can pick up to ramp up on roapi development: https://github.com/roapi/roapi/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
