### ISSUE TITLE
Broken support for exploring multiple tables with `columnq console`

### ISSUE THREAD

**Issue by skeggse** [roapi/roapi#321]
https://github.com/roapi/roapi/pull/304 introduced a regression in support for multiple `--table` flags per https://github.com/roapi/roapi/pull/304#discussion_r1536738741.

**Comment by houqp** [comment]
Thanks for catching that @skeggse , we are missing a `.action(clap::ArgAction::Append)` there, do you mind sending a PR?

**Comment by houqp** [comment]
this is now fixed in the main branch

**Comment by skeggse** [comment]
That was fast, thanks! I had "submit a PR" in the back of my head this last week, and when I went to go look it was already done :tada:
