### ISSUE TITLE
Unable to connect to delta lake tables on adls gen2 storage

### ISSUE THREAD

**Issue by prabodh516** [roapi/roapi#323]
Hi

I am trying to access delta lake tables on adls gen2 
Below is my config.yaml

tables:
  - name: my-table
    uri: abfss://my-dl-tables@accountname.dfs.core.windows.net/my-table
    option:
      format: "delta"
      use_memory_table: false

I have set below environment variables as well

AZURE_STORAGE_ACCOUNT_NAME
AZURE_STORAGE_ACCOUNT_KEY

But i keep getting below exception

Failed to create Roapi context: Whatever { source: Some(TableError { source: LoadDelta { source: OpenTable { source: InvalidTableLocation("**Unknown scheme: abfss**") } } }), message: "Failed to load table", backtrace: Backtrace [{ fn: "roapi::startup::Application::build::{{closure}}" }, { fn: "roapi::main::{{closure}}" }, { fn: "roapi::main" }

Pls advice where I am going wrong.

**Comment by houqp** [comment]
you can try the uri schemes documented in the official delta doc: https://delta-io.github.io/delta-rs/python/usage.html?highlight=adls#loading-a-delta-table
