### ISSUE TITLE
Add support for binary data 

### ISSUE THREAD

**Issue by 0x26res** [roapi/roapi#336]
I have tables with some binary data:

```
import pyarrow as pa
import pyarrow.parquet as pq

table = pa.table(
    {
        "col1": ["A", "B", "C"],
        "col2": [b"D", b"E", b"F"],
    }
)

pq.write_table(table, "/tmp/test.parquet")
```

```shell
roapi --table "foo=/tmp/test.parquet" --addr-postgres=0.0.0.0:5433
```

```shell
curl "http://localhost:8080/api/tables/foo?columns=col1"   
[{"col1":"A"},{"col1":"B"},{"col1":"C"}]
curl "http://localhost:8080/api/tables/foo?columns=col2"
{"code":500,"error":"json_serialization","message":"Failed to serialize payload into JSON"}
```

Could the binary data be sent using base64 encoding in json?

**Comment by houqp** [comment]
serialization code is managed at https://github.com/roapi/roapi/blob/7f0d4bf941c048f2c2214539943d34cbba2fec74/columnq/src/encoding/json.rs#L9. recommend checking out the upstream arrow-rs crate to see if they have binary support by default.

**Comment by 0x26res** [comment]
Thanks @houqp. The arrow json documentation suggests converting the binary to string using base64. https://docs.rs/arrow-json/latest/arrow_json/

So basically I would have to do the transformation myself on the parquet file I'm trying to host. Which makes sense. 

I'll close the issue.
