### ISSUE TITLE
Feature Request: Support for Dynamic Table Deletion

### ISSUE THREAD

**Issue by mrchypark** [roapi/roapi#340]
## Current Situation
Currently, it's possible to add tables dynamically through the API.

## Feature Request
To improve resource management, it would be beneficial to also provide functionality for table deletion.

## Rationale
Implementing dynamic table deletion would allow for more effective resource management. This feature would complement the existing ability to add tables dynamically, providing users with greater control over their data structures.

## Potential Benefits

- More efficient use of memory and storage resources
- Improved flexibility in managing data structures
- Enhanced ability to clean up temporary or obsolete tables

## Questions

- Is this feature already on the roadmap?
- Are there any technical challenges that might make this difficult to implement?
- Would this feature require significant changes to the existing architecture?

Thank you for considering this feature request. Let me know if you need any additional information or clarification.

**Comment by houqp** [comment]
@mrchypark this should be very easy to add, you can checkout the code that adds table dynamically at https://github.com/roapi/roapi/blob/7f0d4bf941c048f2c2214539943d34cbba2fec74/roapi/src/api/register.rs#L33.

to delete a table, we can just delete the table from the hash table. I am happy to review the PR if you are interested in giving it a try.
