### ISSUE TITLE
issue compiling roapi-http v0.1.13  could not compile `actix-cors`

### ISSUE THREAD

**Issue by Diluted** [roapi/roapi#43]
Hello,
I try to compile roapi-http from the [source zip](https://github.com/roapi/roapi/archive/refs/tags/roapi-http-v0.1.3.zip)

I have an error when I compile 

`cargo install --verbose --path ./roapi-http --bin roapi-http`
building
...
...

```
error[E0053]: method `error_response` has an incompatible type for trait                                                              │
  --> /usr/local/cargo/git/checkouts/actix-extras-3214827614a42f65/ab3bdb6/actix-cors/src/error.rs:53:5                               │
   |                                                                                                                                  │
53 |     fn error_response(&self) -> HttpResponse {                                                                                   │
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `BaseHttpResponse`, found struct `actix_web::HttpResponse`          │
   |                                                                                                                                  │
   = note: expected fn pointer `fn(&CorsError) -> BaseHttpResponse<actix_web::dev::Body>`                                             │
              found fn pointer `fn(&CorsError) -> actix_web::HttpResponse`                                                            │
                                                                                                                                      │
error: aborting due to previous error                                                                                                 │
                                                                                                                                      │
For more information about this error, try `rustc --explain E0053`.                                                                   │
error: could not compile `actix-cors`                                                                                                 │
```

**Comment by houqp** [comment]
@Diluted could you share the rust version here?

**Comment by Diluted** [comment]
rust version 1.51 because 1.50 gives me another set of error with flatbuffers regarding const generics:

error[E0658]: const generics are unstable
   |
28 | pub struct Array<'a, T: 'a, const N: usize>(&'a [u8], PhantomData<T>);
   |                                   ^
   |
   = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information

**Comment by houqp** [comment]
I can reproduce this on my end as well, looks like `cargo install` doesn't honor the `Cargo.lock` file shipped in the source. From my cargo build log, I see:

```
actix-web v4.0.0-beta.6
```

But in the lock file, it's pinned to `beta.4`.

As a work around, you could use `cargo build` to produce the binary, then manually install it into your PATH.

**Comment by houqp** [comment]
released v0.2.0. I am going to try to migrate away from actix-web because it's not being actively maintained anymore unfortuately.

**Comment by houqp** [comment]
welp, looks like even pinning the version in `Cargo.toml` is not enough to make `cargo install` work :thinking:

**Comment by houqp** [comment]
oh well, turns out this is a well known problem, see https://github.com/rust-lang/cargo/issues/7169. I will update all instructions to run `cargo install` with `--locked` argument.

**Comment by houqp** [comment]
updated docs everywhere.

**Comment by Diluted** [comment]
@houqp thanks, I will have a look today or later this week
