### ISSUE TITLE
Azure Data Lake Gen 2 support

### ISSUE THREAD

**Issue by dispanser** [roapi/roapi#74]
Delta-rs (and soon, datafusion) will support ADL2, and I think it would be great  to also have this in ROAPI. 

If I had to implement it, I'd have a closer look at the implementation in [delta-rs](https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/azure.rs) but I'm open to other suggestions.

**Comment by houqp** [comment]
That sounds good, I also use the s3 storage backend in delta-rs as the inspiration for roapi's s3 io module.

**Comment by jychen7** [comment]
I am not familiar with Azure, but looks like ADLS Gen 2 `adfs://` and `adfss://` are supported by `object_store` and thus done in https://github.com/roapi/roapi/pull/250?

**Comment by houqp** [comment]
I think so, thanks @jychen7 !
