### ISSUE TITLE
Looking into source of logging overhead

### ISSUE THREAD

**Issue by houqp** [roapi/roapi#85]
https://tech.marksblogg.com/roapi-rust-data-api.html mentioned that changing logging level from info to error resulted in 50% speed boost, this is certainly not expected :(

**Comment by houqp** [comment]
@Dandandan I am not seeing info logging from sqlparser, looks like it's only using `log::debug` at the moment?

**Comment by Dandandan** [comment]
Ah yes - good find. Sounds like a good idea :+1:

**Comment by houqp** [comment]
Thanks @marklit for the tip. I will verify the logging overhead once we moved to a new web framework and optimize it if it still turns out to be an issue.
