### ISSUE TITLE
docker is not working due to GLIBC issue: roapi-http: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by roapi-http)

### ISSUE THREAD

**Issue by M-M-M-M** [roapi/roapi#86]
Running `docker run -t --rm -p 8080:8080 ghcr.io/roapi/roapi-http:latest --addr 0.0.0.0:8080 \
    --table "uk_cities=test_data/uk_cities_with_headers.csv" \
    --table "test_data/spacex_launches.json"`

is generating error:

```roapi-http: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by roapi-http)```

**Comment by houqp** [comment]
I will take a look into this today, in the mean time, you can try an older version as a workaround:

```
docker run -t --rm -p 8080:8080 ghcr.io/roapi/roapi-http:v0.3.4 --addr 0.0.0.0:8080 --table "uk_cities=test_data/uk_cities_with_headers.csv" --table "test_data/spacex_launches.json"
```
